version: "3.9"
services:
  frontend:
      container_name: yobom_sorvetes2025_Frontend
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports: 
        - "3000:3000" # Porta do frontend
      volumes:
        - ./frontend:/app
      networks:
        - app-network
networks:
  app-network:
    driver: bridge
